# Starter pipeline


# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Compile and and run tests'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'DataStructures.sln'
    arguments: '--configuration=Release --verbosity=n'

- script: dotnet test DataStructures.sln --logger trx  --collect "Code coverage"
- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    projects: 'DataStructures\DataStructures.csproj'
    arguments: '--include-symbols --include-source --configuration=Release'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    projects: 'DataStructures\DataStructures.csproj'
    arguments: '--include-symbols --include-source --configuration=Release'
  

