# Starter pipeline


# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

name: $(BuildDefinitionName)_$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

pool:
  vmImage: 'windows-latest'

steps:
- task: DotNetCoreCLI@2
  displayName: build solution release
  inputs:
    command: 'build'
    projects: 'DataStructures.UI.sln'
    arguments: '--configuration=Release --verbosity=n'

steps:
- task: DotNetCoreCLI@2
  displayName: build solution debug for nuget
  inputs:
    command: 'build'
    projects: 'DataStructures.UI.sln'
    arguments: '--configuration=Debug --verbosity=n'

- script: dotnet test DataStructures.sln --logger trx  --collect "Code coverage"
  displayName: 'run test'
  condition: succeeded()

- task: PublishTestResults@2
  displayName: publish test results
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- task: DotNetCoreCLI@2
  displayName: create nuget DataStructures;Algorithms.Graph
  condition: succeeded()
  inputs:
    command: 'pack'
    arguments: '--include-symbols --include-source --output $(Build.ArtifactStagingDirectory)'
    packagesToPack: '**/DataStructures.csproj;**/Algorithms.Graph.csproj;'
    includesymbols: true
    includesource: true
    versioningScheme: 'byBuildNumber'
    verbosityPack: 'Normal'

- task: DotNetCoreCLI@2
  displayName: build DataStructures.UI
  inputs:
    command: 'build'
    projects: '**/**/DataStructures.UI.csproj'

- task: DotNetCoreCLI@2
  displayName: create nuget DataStructures.UI
  condition: succeeded()
  inputs:
    command: 'pack'
    arguments: '--include-symbols --include-source --output $(Build.ArtifactStagingDirectory)'
    packagesToPack: '**/**/DataStructures.UI.csproj;'
    includesymbols: true
    includesource: true
    versioningScheme: 'byBuildNumber'
    verbosityPack: 'Normal'

- task: DotNetCoreCLI@2
  displayName: 'creating DataStructures.Demo in $(build.artifactstagingdirectory)'
  inputs:
    command: 'publish'
    publishWebProjects: false
    arguments: '-r win-x64 -c debug --no-restore /p:PublishSingleFile=true -o $(build.artifactstagingdirectory)'
    workingDirectory: 'DataStructures.UI/DataStructures.UI.Demo'

- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: push
    publishVstsFeed: 'get-the-solution'
    allowPackageConflicts: true

- task: PublishBuildArtifacts@1
  condition: succeededOrFailed()
  displayName: "Upload Artifacts"
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'DataStructures' 